name: PR auto merge
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+09:00"
      - name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          MERGE_LABELS: "${{steps.current-time.outputs.formattedTime}}"
          MERGE_METHOD: "squash"
          GITHUB_TOKEN: "${{ secrets.TOKEN }}"
